### ISSUE TITLE
VanillaJs example

### ISSUE THREAD

**Issue by samlinux** [buildwithjuno/examples#1]
If I try to test the vanillaJS example, there is an error after the login with Internet Identity. See the picture attached. This is the example you publish on the github page.

**Comment by samlinux** [comment]
![exampleVanillajs](https://user-images.githubusercontent.com/424294/218960472-aa191a59-117e-4a23-88e1-de4a8ede80b5.png)

**Comment by peterpeterparker** [comment]
Apologies for the late answer, somehow I did not received the notification.

It should be fixed now, if you pull last version. The satellite id was incorrect in the sample.

Thanks for the report!

<img width="1536" alt="Capture d’écran 2023-03-11 à 08 27 18" src="https://user-images.githubusercontent.com/16886711/224471331-9384723f-4c71-4d28-bc3e-f37aa1b5b7cd.png">

**Comment by peterpeterparker** [comment]
Also redeploy, here correct link with correct salitte id [https://xo2hm-lqaaa-aaaal-ab3oa-cai.icp0.io](https://xo2hm-lqaaa-aaaal-ab3oa-cai.icp0.io)
